services:
  node:
    build:
      context: .
      dockerfile: Dockerfile.node
    ports:
      - "5173:5173"

  python:
    build:
      context: .
      dockerfile: Dockerfile.python
    ports:
      - "8088:8088"
